# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 650)
        Form.setStyleSheet("background-color: #f5f7fa;")
        self.titleLabel = QtWidgets.QLabel(Form)
        self.titleLabel.setGeometry(QtCore.QRect(0, 30, 1000, 60))
        self.titleLabel.setStyleSheet("color: #2c3e50;\n"
"font-size: 28px;\n"
"font-weight: bold;\n"
"background: transparent;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.subTitle = QtWidgets.QLabel(Form)
        self.subTitle.setGeometry(QtCore.QRect(0, 85, 1000, 25))
        self.subTitle.setStyleSheet("color: #7f8c8d;\n"
"font-size: 13px;\n"
"background: transparent;")
        self.subTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subTitle.setObjectName("subTitle")
        self.leftPanel = QtWidgets.QWidget(Form)
        self.leftPanel.setGeometry(QtCore.QRect(50, 140, 280, 400))
        self.leftPanel.setStyleSheet("background: transparent;")
        self.leftPanel.setObjectName("leftPanel")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftLayout.setContentsMargins(0, 0, 0, 0)
        self.leftLayout.setSpacing(20)
        self.leftLayout.setObjectName("leftLayout")
        self.pushButton = QtWidgets.QPushButton(self.leftPanel)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #3498db,\n"
"        stop:1 #2980b9);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #5dade2,\n"
"        stop:1 #3498db);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.leftLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.leftPanel)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #27ae60,\n"
"        stop:1 #1e8449);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #52be80,\n"
"        stop:1 #27ae60);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.leftLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.leftPanel)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background: #bdc3c7;\n"
"    color: #2c3e50;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #aab7b8;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.leftLayout.addWidget(self.pushButton_3)
        self.rightPanel = QtWidgets.QFrame(Form)
        self.rightPanel.setGeometry(QtCore.QRect(360, 140, 590, 400))
        self.rightPanel.setStyleSheet("background: white;\n"
"border: none;\n"
"border-radius: 15px;")
        self.rightPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightPanel.setObjectName("rightPanel")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightLayout.setContentsMargins(15, 15, 15, 15)
        self.rightLayout.setObjectName("rightLayout")
        self.label_2 = QtWidgets.QLabel(self.rightPanel)
        self.label_2.setStyleSheet("border: none;\n"
"background: #ecf0f1;\n"
"border-radius: 10px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/img/img/R-C.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.rightLayout.addWidget(self.label_2)
        self.bottomTip = QtWidgets.QLabel(Form)
        self.bottomTip.setGeometry(QtCore.QRect(0, 580, 1000, 40))
        self.bottomTip.setStyleSheet("color: #95a5a6;\n"
"font-size: 12px;\n"
"background: transparent;")
        self.bottomTip.setAlignment(QtCore.Qt.AlignCenter)
        self.bottomTip.setObjectName("bottomTip")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "泪膜破裂检测系统"))
        self.titleLabel.setText(_translate("Form", "泪膜破裂检测系统"))
        self.subTitle.setText(_translate("Form", "Tear Film Break-up Detection System"))
        self.pushButton.setText(_translate("Form", "图像检测"))
        self.pushButton_2.setText(_translate("Form", "视频检测"))
        self.pushButton_3.setText(_translate("Form", "退出系统"))
        self.bottomTip.setText(_translate("Form", "基于 Placido 环图像的泪膜破裂自动检测"))
import csy_rc
