# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/video.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 650)
        Form.setStyleSheet("background-color: #f5f7fa;")
        self.pageTitle = QtWidgets.QLabel(Form)
        self.pageTitle.setGeometry(QtCore.QRect(0, 20, 1000, 50))
        self.pageTitle.setStyleSheet("color: #2c3e50;\n"
"font-size: 22px;\n"
"font-weight: bold;\n"
"background: transparent;")
        self.pageTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.pageTitle.setObjectName("pageTitle")
        self.originalFrame = QtWidgets.QFrame(Form)
        self.originalFrame.setGeometry(QtCore.QRect(50, 90, 430, 400))
        self.originalFrame.setStyleSheet("background: white;\n"
"border: none;\n"
"border-radius: 12px;")
        self.originalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.originalFrame.setObjectName("originalFrame")
        self.originalLayout = QtWidgets.QVBoxLayout(self.originalFrame)
        self.originalLayout.setContentsMargins(10, 10, 10, 10)
        self.originalLayout.setObjectName("originalLayout")
        self.labelTitle1 = QtWidgets.QLabel(self.originalFrame)
        self.labelTitle1.setMaximumHeight(35)
        self.labelTitle1.setStyleSheet("color: #3498db;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"background: #ebf5fb;\n"
"border-radius: 8px;")
        self.labelTitle1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle1.setObjectName("labelTitle1")
        self.originalLayout.addWidget(self.labelTitle1)
        self.label = QtWidgets.QLabel(self.originalFrame)
        self.label.setStyleSheet("background: #ecf0f1;\n"
"border-radius: 8px;")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.originalLayout.addWidget(self.label)
        self.resultFrame = QtWidgets.QFrame(Form)
        self.resultFrame.setGeometry(QtCore.QRect(520, 90, 430, 400))
        self.resultFrame.setStyleSheet("background: white;\n"
"border: none;\n"
"border-radius: 12px;")
        self.resultFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resultFrame.setObjectName("resultFrame")
        self.resultLayout = QtWidgets.QVBoxLayout(self.resultFrame)
        self.resultLayout.setContentsMargins(10, 10, 10, 10)
        self.resultLayout.setObjectName("resultLayout")
        self.labelTitle2 = QtWidgets.QLabel(self.resultFrame)
        self.labelTitle2.setMaximumHeight(35)
        self.labelTitle2.setStyleSheet("color: #27ae60;\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"background: #e9f7ef;\n"
"border-radius: 8px;")
        self.labelTitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle2.setObjectName("labelTitle2")
        self.resultLayout.addWidget(self.labelTitle2)
        self.label_2 = QtWidgets.QLabel(self.resultFrame)
        self.label_2.setStyleSheet("background: #ecf0f1;\n"
"border-radius: 8px;")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.resultLayout.addWidget(self.label_2)
        self.buttonFrame = QtWidgets.QWidget(Form)
        self.buttonFrame.setGeometry(QtCore.QRect(0, 510, 1000, 80))
        self.buttonFrame.setStyleSheet("background: transparent;")
        self.buttonFrame.setObjectName("buttonFrame")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.buttonFrame)
        self.buttonLayout.setContentsMargins(50, 0, 50, 0)
        self.buttonLayout.setSpacing(20)
        self.buttonLayout.setObjectName("buttonLayout")
        self.pushButton = QtWidgets.QPushButton(self.buttonFrame)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 45))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background: #3498db;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #2980b9;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.buttonLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.buttonFrame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(140, 45))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: #27ae60;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #1e8449;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonLayout.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.buttonFrame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 45))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background: #bdc3c7;\n"
"    color: #2c3e50;\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #aab7b8;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonLayout.addWidget(self.pushButton_3)

        # 移除进度条相关控件，不再需要
        self.videoSlider = None
        self.timeLabel = None
        self.durationLabel = None

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "视频检测 - 泪膜破裂检测系统"))
        self.pageTitle.setText(_translate("Form", "视频检测"))
        self.labelTitle1.setText(_translate("Form", "原始视频"))
        self.labelTitle2.setText(_translate("Form", "实时分析"))
        self.pushButton.setText(_translate("Form", "选择视频"))
        self.pushButton_2.setText(_translate("Form", "开始/暂停"))
        self.pushButton_3.setText(_translate("Form", "返回"))
